"""added department_head column

Revision ID: 298e16623854
Revises: 4813592f6083
Create Date: 2023-10-02 11:03:33.368167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298e16623854'
down_revision: Union[str, None] = '4813592f6083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('department_head', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'department_head')
    # ### end Alembic commands ###
