"""rename time_created to created_at field in balcklist_token table

Revision ID: 5e975548e1b8
Revises: e58b9ab0ada5
Create Date: 2023-10-03 18:23:18.034820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e975548e1b8'
down_revision: Union[str, None] = 'e58b9ab0ada5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balcklist_token', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('balcklist_token', 'time_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balcklist_token', sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('balcklist_token', 'created_at')
    # ### end Alembic commands ###
