"""rename user_id field

Revision ID: e34a903b3ecc
Revises: 2c3a8a796db9
Create Date: 2023-10-02 15:19:30.879315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34a903b3ecc'
down_revision: Union[str, None] = '2c3a8a796db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
