"""added created_at field in balcklist_token table

Revision ID: e58b9ab0ada5
Revises: 94c85e471915
Create Date: 2023-10-03 18:21:50.022652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58b9ab0ada5'
down_revision: Union[str, None] = '94c85e471915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balcklist_token', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balcklist_token', 'time_created')
    # ### end Alembic commands ###
